do not use uri icons on api 29- as these offer no value and crash
compat library tries to reconstruct them from Uri (bad) and fails with:

    java.lang.IllegalArgumentException: Context is required to resolve the file uri of the icon: content://com.ubergeek42.WeechatAndroid.debug.file_provider/icons/d0bdd18f203a3a206972632e667265652e7371726c
        at androidx.core.graphics.drawable.IconCompat.toIcon(IconCompat.java:572)
        at androidx.core.graphics.drawable.IconCompat.toIcon(IconCompat.java:529)
        at androidx.core.app.Person.toAndroidPerson(Person.java:177)
        at androidx.core.app.NotificationCompat$MessagingStyle$Message.toAndroidMessage(NotificationCompat.java:4002)
        at androidx.core.app.NotificationCompat$MessagingStyle.apply(NotificationCompat.java:3554)
        at androidx.core.app.NotificationCompatBuilder.build(NotificationCompatBuilder.java:312)
        at androidx.core.app.NotificationCompat$Builder.build(NotificationCompat.java:2346)
        at com.ubergeek42.WeechatAndroid.notifications.NotificatorKt.showHotNotification(Notificator.kt:208)
        at com.ubergeek42.WeechatAndroid.notifications.HotlistKt.pushUpdate(Hotlist.kt:151)
        at com.ubergeek42.WeechatAndroid.notifications.HotlistKt.access$pushUpdate(Hotlist.kt:1)
        at com.ubergeek42.WeechatAndroid.notifications.HotlistBuffer.updateOnHotLine(Hotlist.kt:120)