prevent uiLines adapter updates from running out of order
Weechat.runOnMainThreadASAP() would run code on main thread either
right away or posted. thus a later update requested from main thread
could run before earlier update requested from worker thread

this could result in a crash such as the one below; a few similar
crashes were observed as well

to reproduce the crash, open a few buffers and execute the following
in a few buffers:

    /eval /trigger addreplace message1_${buffer} timer 1496;0;0 "" "" "/print -buffer ${buffer.full_name} ${buffer} hello world one two three four five six seven eight!"
    /eval /trigger addreplace message2_${buffer} timer 496;0;0 "" "" "/print -buffer ${buffer.full_name} ${buffer} hello world one two three four five"
    /eval /trigger addreplace highlight_${buffer} timer 5128;0;0 "" "" "/print -tags notify_highlight -buffer ${buffer.full_name} ${buffer} highlight!!"

then limit loaded lines to 5 and press on the hot buffer button to
switch buffers a lot

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ubergeek42.WeechatAndroid.debug, PID: 27038
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 455(offset:-1).state:459 com.ubergeek42.WeechatAndroid.views.AnimatedRecyclerView{94e1a58 V.ED.V... ......ID 0,0-1080,1939 #7f080058 app:id/chatview_lines}, adapter:com.ubergeek42.WeechatAndroid.adapters.ChatLinesAdapter@ec1f195, layout:androidx.recyclerview.widget.LinearLayoutManager@a5837b1, context:com.ubergeek42.WeechatAndroid.WeechatActivity@8b7caa7
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5923)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:587)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3639)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:22466)