fix a crash while inflating layout on api 21
see https://stackoverflow.com/a/47926165/1449683

AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ubergeek42.WeechatAndroid.debug, PID: 10490
    android.view.InflateException: Binary XML file line #74: Binary XML file line #74: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #74: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
    ...
AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: android.content.res.Resources$NotFoundException: Drawable com.ubergeek42.WeechatAndroid.debug:color/toolbar_icon with resource ID #0x7f05009c
     Caused by: android.content.res.Resources$NotFoundException: File res/color/toolbar_icon.xml from drawable resource ID #0x7f05009c
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
    ...
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #3: <item> tag requires a 'drawable' attribute or child tag defining a drawable
        at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:183)