Add R8 -keep rule for org.apache.commons.codec.*Exception
This resolves a crash when pressing on the paperclip icon on Android 6.
This is probably not a good way to solve the issue,
since it fixes the symptom, and not the cause.

Function com.ubergeek42.WeechatAndroid.upload.FileChooserKt#chooseFiles,
that calls com.ubergeek42.WeechatAndroid.upload.UploadConfigKt#validateUploadConfig,
which looks like this:

fun validateUploadConfig() {
    if (Config.uploadUri.isBlank()) throw UploadConfigValidationError("Upload URL not set")
}

gets the following bytecode after R8 gets its funny little appendages
into the code (many lines omitted):

.method public static final chooseFiles(Landroidx/fragment/app/Fragment;Lcom/ubergeek42/WeechatAndroid/upload/Target;)V
    ...
    new-instance p1, Lorg/apache/commons/codec/DecoderException;
    const-string v2, "Upload URL not set"
    invoke-direct {p1, v2, v0}, Lorg/apache/commons/codec/DecoderException;-><init>(Ljava/lang/String;I)V
    ...

It seems that UploadConfigValidationError gets rewritten as DecoderException,
which is possible as the former is not explicitly caught.
On later Android versions this works just fine, however,
on Android 6, this class, which is usually provided by the system,
apparently lacks the called init method, which leads to a crash:

2022-06-23 21:46:38.347 16098-16098/com.ubergeek42.WeechatAndroid.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ubergeek42.WeechatAndroid.dev, PID: 16098
    Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
    java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;I)V in class Lorg/apache/commons/codec/DecoderException; or its super classes (declaration of 'org.apache.commons.codec.DecoderException' appears in /system/framework/org.apache.http.legacy.boot.jar)
        at com.ubergeek42.WeechatAndroid.upload.FileChooserKt.chooseFiles(SourceFile:37)
        at com.ubergeek42.WeechatAndroid.fragments.BufferFragment$$ExternalSyntheticLambda2.onClick(SourceFile:101)
        at android.view.View.performClick(View.java:5204)
        at android.view.View$PerformClick.run(View.java:21158)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5461)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Keeping the method resolves this particular crash.